global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wikisurge-api'
    static_configs:
      - targets: ['wikisurge-api:2112']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'wikisurge-processor'
    static_configs:
      - targets: ['wikisurge-processor:2112']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'wikisurge-ingestor'
    static_configs:
      - targets: ['wikisurge-ingestor:2112']
    metrics_path: /metrics
    scrape_interval: 15s